### ISSUE TITLE
Build issues with jinja2.ext

### ISSUE THREAD

**Issue by saraahwallace** [openvax/vaxrank#197]
Hi I am having problems running vaxrank, I am getting this error message.

(vaxrank-dev-env) -bash-4.2$ vaxrank \ --vcf /Volumes/archive/cancergeneticslab/SarahWallace/pVACseq/ensembl-vep/VEP_annotated_SSM3_somatic_hc_SNP.vcf \ --bam /Volumes/archive/cancergeneticslab/SarahWallace/align_Cont_only_1_Aligned.sortedByCoord.out.bam \ --mhc-predictor netmhcpan4 \ --vaccine-peptide-length 25 \ --mhc-peptide-lengths 8-12 \ --mhc-alleles H2-Kb \ --padding-around-mutation 5 \ --min-alt-rna-reads 3 \ --output-ascii-report SNP_vaccine-peptides.txt \ --output-pdf-report SNP_vaccine-peptides.pdf \ --output-html-report SNP_vaccine-peptides.html        
Traceback (most recent call last):
  File "/Volumes/archive/userdata/student_users/sarahwallace/.conda/envs/vaxrank-dev-env/bin/vaxrank", line 5, in <module>
    from vaxrank.cli import main
  File "/Volumes/archive/userdata/student_users/sarahwallace/.conda/envs/vaxrank-dev-env/lib/python3.8/site-packages/vaxrank/cli.py", line 36, in <module>
    from .report import (
  File "/Volumes/archive/userdata/student_users/sarahwallace/.conda/envs/vaxrank-dev-env/lib/python3.8/site-packages/vaxrank/report.py", line 37, in <module>
    JINJA_ENVIRONMENT = jinja2.Environment(
  File "/Volumes/archive/userdata/student_users/sarahwallace/.conda/envs/vaxrank-dev-env/lib/python3.8/site-packages/jinja2/environment.py", line 363, in __init__
    self.extensions = load_extensions(self, extensions)
  File "/Volumes/archive/userdata/student_users/sarahwallace/.conda/envs/vaxrank-dev-env/lib/python3.8/site-packages/jinja2/environment.py", line 117, in load_extensions
    extension = t.cast(t.Type["Extension"], import_string(extension))
  File "/Volumes/archive/userdata/student_users/sarahwallace/.conda/envs/vaxrank-dev-env/lib/python3.8/site-packages/jinja2/utils.py", line 149, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)
AttributeError: module 'jinja2.ext' has no attribute 'autoescape'

**Comment by biolxy** [comment]
> 您好，我在运行 vaxrank 时遇到问题，收到此错误消息。
> 
> （vaxrank-dev-env）-bash-4.2$ vaxrank \ --vcf /Volumes/archive/cancer Geneticslab/SarahWallace/pVACseq/ensembl-vep/VEP_annotated_SSM3_somatic_hc_SNP.vcf \ --bam /Volumes/archive/cancer Geneticslab/SarahWallace/ SortedByCoord.out.bam \ --mhc-预测器 netmhcpan4 \ --疫苗肽长度 25 \ --mhc- 肽长度 8-12 \ --mhc 等位基因 H2-Kb \ --padding-around-mutation 5 \ --min-alt-rna-reads 3 \ --output-ascii-report SNP_vaccine-peptides.txt \ --output-pdf-report SNP_vaccine-peptides.pdf \ --output-html-report SNP_vaccine-peptides。 html 回溯（最近一次调用最后一次）： 文件“/Volumes/archive/userdata/student_users/sarahwallace/.conda/envs/vaxrank-dev-env/bin/vaxrank”，第5行，来自 vaxrank.cli import main 文件“/Volumes/archive/userdata/student_users/sarahwallace/.conda/envs/vaxrank-dev-env/lib/python3.8/site-packages/vaxrank/cli.py”，第36行，来自 .report import ( 文件“/Volumes/archive/userdata/student_users/sarahwallace/.conda/envs/vaxrank-dev-env/lib/python3.8/site-packages/vaxrank/report.py”，第37行，位于 JINJA_ENVIRONMENT = jinja2。环境（ 文件“/Volumes/archive/userdata/student_users/sarahwallace/.conda/envs/vaxrank-dev-env/lib/python3.8/site-packages/jinja2/environment.py”，第363行，在**init** self中.extensions中= load_extensions(self, 扩展) 文件“/Volumes/archive/userdata/student_users/sarahwallace/.conda/envs/vaxrank-dev-env/lib/python3.8/site-packages/jinja2/environment.py” ，第117行，在load_extensions中 扩展名 = t.cast(t.Type["Extension"], import_string(extension)) 文件“/Volumes/archive/userdata/student_users/sarahwallace/.conda/envs/vaxrank-dev-env/lib/python3.8 /site-packages/jinja2/utils.py"，第149行，在 import_string return getattr( **import** (module, None, None, [obj]), obj) AttributeError: 模块 'jinja2.ext' 没有属性 'autoescape'

You can downgrade the jinja2 version to 3.0.0 after installing vaxrank
```bash
pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple Jinja2==3.0.0
```
